describe('catch-async-errors', () => {
  it('should catch an error', () => {
    // TODO
  })
})
